"""Broker adapter capability contract."""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from autostrategy.brokers.models import (
    AccountHealth,
    BrokerEvent,
    BrokerOrder,
    ChildOrder,
    FtAccount,
    FundSnapshot,
    MonitoringSnapshot,
    OrderIntent,
    PositionSnapshot,
)


class BrokerAdapter(Protocol):
    def connect(self) -> list[FtAccount]: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, AccountHealth]: ...
    def list_accounts(self) -> list[FtAccount]: ...
    def get_funds(self, trade_account: str, broker_id: str) -> FundSnapshot: ...
    def get_positions(self, trade_account: str, broker_id: str) -> list[PositionSnapshot]: ...
    def submit_order(self, intent: OrderIntent) -> BrokerOrder: ...
    def cancel_orders(self, parent_order_ids: list[str]) -> None: ...
    def get_orders(self, trade_account: str, broker_id: str) -> list[BrokerOrder]: ...
    def get_child_orders(self, parent_order_id: str) -> list[ChildOrder]: ...
    def get_monitoring(self, ft_account: str) -> MonitoringSnapshot: ...
    def stream_events(self) -> AsyncIterator[BrokerEvent]: ...
